package common

// Pave the way for future internationalization operations
var (
	ZHCNUiMessage = map[string]string{
		"execute":                     "执行",
		"cancel":                      "取消",
		"intro":                       "请输入AK，SK和 Host",
		"enterAK":                     "请在此输入您的AK",
		"enterSK":                     "请在此输入您的SK",
		"enterHost":                   "请输入您部署Func的主机，例如：http://<host>:<port>/ 或 https://<host>：<port>/",
		"printResult":                 "执行结果将显示在此处！",
		"domainError":                 "Host格式不正确。请参阅以下示例格式: http://<host>:<port>/ or https://<host>:<port>/",
		"echoTestSuccess":             "回声测试成功！即将开始开启部署流程",
		"echoTestFailed":              "回声测试失败！请检查AK，SK和Host是否正确以及Func是否已创建Access Key",
		"replaceScriptMarket":         "转换系统脚本市场",
		"pullUpScriptMarket":          "正在拉取脚本市场代码,请稍等...",
		"pullScriptMarketCodeSuccess": "拉取脚本市场代码成功!",
		"pullScriptMarketCodeFailed":  "拉取脚本市场代码失败!请联系开发人员",
		"installScriptSetSuccess":     "脚本集安装成功!",
		"installScriptSetFailed":      "脚本集安装失败!请联系开发人员",
		"addAuthorizationLinkSuccess": "授权链接添加成功!",
		"addAuthorizationLinkFailed":  "授权链接添加失败!请联系开发人员",
		"uploadDocSuccess":            "更新接口文档成功!",
		"uploadDocFailed":             "更新接口文档失败!请联系开发人员",
		"gzipFileFailed":              "压缩文件包失败!请联系开发人员",
		"uploadPackFailed":            "上传至Func文件并解压操作失败!请联系开发人员",
		"fileServeNote":               "请求结果转换系统所属文件服务【勿删!】",
		"addFileServeFailed":          "添加文件服务失败!请联系开发人员",
		"deploySuccess":               "系统部署成功!",
		"desc":                        "初始用户名和密码为:admin/admin",
	}
	ENUiMessage = map[string]string{
		"execute":                     "execute",
		"cancel":                      "cancel",
		"intro":                       "Please enter the AK, SK and Host",
		"enterAK":                     "Please enter the your AK",
		"enterSK":                     "Please enter the your SK",
		"enterHost":                   "Enter the host on which you are deploying Func, eg: http://<host>:<port>/ or https://<host>:<port>/",
		"printResult":                 "The result of the execution will be displayed here!",
		"domainError":                 "domain format is incorrect. See the following example format: http://<host>:<port>/ or https://<host>:<port>/",
		"echoTestSuccess":             "Echo test successful! The deployment process is about to begin",
		"echoTestFailed":              "Echo test failed! Please check that the AK, SK, and Host are correct and that Func has created an Access Key",
		"replaceScriptMarket":         "replace-script-market",
		"pullUpScriptMarket":          "Pulling script market code, please wait...",
		"pullScriptMarketCodeSuccess": "Pull script market code successful!",
		"pullScriptMarketCodeFailed":  "Pull script marketplace code failed!, contact the developer",
		"installScriptSetSuccess":     "The script set was installed successfully!",
		"installScriptSetFailed":      "Script set installation failed! Contact the developer",
		"uploadDocSuccess":            "Update interface documentation successful!",
		"uploadDocFailed":             "Failed to update interface documentation! Contact the developer",
		"gzipFileFailed":              "Compressed package failed! Contact the developer",
		"uploadPackFailed":            "Upload to Func file and unzip failed! Contact the developer",
		"fileServeNote":               "Request the file service to which the result conversion system belongs [Do not delete!]",
		"addFileServeFailed":          "Add file service failed! Contact the developer",
		"deploySuccess":               "System deployed successfully!!",
		"desc":                        "The initial username and password are: admin/admin",
	}
)
